CREATE TABLE Inventario (
Id NUMERIC PRIMARY KEY,
Producto VARCHAR2(100), 
Cantidad NUMERIC DEFAULT 0 NOT NULL,
Precio NUMERIC DEFAULT 0 NOT NULL
)

SELECT * FROM Inventario; 

ALTER TABLE Inventario ADD COLUMN Subtotal NUMERIC;

