CREATE TABLE cliente
   (
   id_cliente NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
   codigo_cliente number(10,0) not null ,
   nombre varchar2(100) not null,
   estadoCivil varchar2(10) default 'SOLTERO' not null,
   edad number(3,0) default 0 not null,
  CONSTRAINT pk_cliente PRIMARY KEY (id_cliente)
 
   );

CREATE TABLE tiempo
   (
   id_tiempo NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
   anio int,
   mes int,
   dia int,
   CONSTRAINT pk_tiempo PRIMARY KEY (id_tiempo)
   );


 
CREATE TABLE ventas
   (    
   id_tiempo NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
   id_cliente numeric(10,0) not null,
   Ingreso numeric,
   costo numeric,
     CONSTRAINT pk_ventas PRIMARY KEY (id_tiempo, id_cliente)  ,
   foreign key (id_tiempo) references tiempo,
   foreign key (id_cliente) references cliente
   );

insert into tiempo (anio, mes, dia)
with row_generator as (
SELECT to_date('01012000','ddmmyyyy') + LEVEL - 1 DT
FROM sys.dual
CONNECT BY LEVEL <=
to_number(to_date('31122017','ddmmyyyy') -
to_date('01012015','ddmmyyyy')) +1 )
SELECT DISTINCT extract(year from DT) as anio, extract(month from DT) as mes, extract(day from DT) as dia
from row_generator
order by 1,2,3;

Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('100','cliente 1','SOLTERO','35');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('101','cliente 2','SOLTERO','33');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('102','cliente 3','SOLTERO','34');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('103','cliente 4','SOLTERO','36');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('104','cliente 5','SOLTERO','37');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('105','cliente 6','SOLTERO','40');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('106','cliente 7','SOLTERO','41');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('107','cliente 8','SOLTERO','42');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('108','cliente 9','SOLTERO','43');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('109','cliente 10','SOLTERO','44');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('110','cliente 11','SOLTERO','45');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('111','cliente 12','SOLTERO','46');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('112','cliente 13','SOLTERO','47');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('113','cliente 14','SOLTERO','48');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('114','cliente 15','SOLTERO','49');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('115','cliente 16','SOLTERO','50');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('116','cliente 17','SOLTERO','51');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('117','cliente 18','SOLTERO','52');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('118','cliente 19','SOLTERO','53');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('119','cliente 20','SOLTERO','54');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('120','cliente 21','SOLTERO','55');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('121','cliente 22','SOLTERO','56');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('122','cliente 23','SOLTERO','57');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('123','cliente 24','SOLTERO','58');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('124','cliente 25','CASADO','59');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('125','cliente 26','CASADO','35');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('126','cliente 27','CASADO','35');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('127','cliente 28','CASADO','34');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('128','cliente 29','CASADO','33');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('129','cliente 30','CASADO','32');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('130','cliente 31','CASADO','33');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('131','cliente 32','CASADO','35');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('132','cliente 33','CASADO','34');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('133','cliente 34','CASADO','68');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('134','cliente 35','CASADO','69');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('135','cliente 36','CASADO','70');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('136','cliente 37','CASADO','71');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('137','cliente 38','CASADO','72');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('138','cliente 39','CASADO','73');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('139','cliente 40','CASADO','74');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('140','cliente 41','CASADO','75');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('141','cliente 42','CASADO','76');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('142','cliente 43','CASADO','77');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('143','cliente 44','CASADO','78');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('144','cliente 45','CASADO','79');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('145','cliente 46','CASADO','80');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('146','cliente 47','CASADO','81');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('147','cliente 48','CASADO','82');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('148','cliente 49','CASADO','83');
Insert into cliente (CODIGO_CLIENTE,NOMBRE,ESTADOCIVIL,EDAD) values ('149','cliente 50','CASADO','84');

INSERT INTO ventas (
    id_tiempo,
    id_cliente,
    ingreso,
    costo
)
SELECT
    tiempo.id_tiempo,    
    cliente.id_cliente,
    dbms_random.value(1,1000) as ingreso,
    dbms_random.value(1,900) as costo
FROM
    tiempo,
    cliente;
